---
- name: MariaDB
  hosts: db
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB-server is running and enabled
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started
