---
- name: Setup users and groups
  hosts: web
  become: true
  vars_files:
    - secret.yml

  tasks:
    - name: Create all users and divide into groups
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        password: "{{ item.password | password_hash('sha512') }}"
        groups: "{{ item.groups }}"
      loop:
        "{{ users }}"


# * `alovelace` and `ghopper` should be added to the `wheel` group.
# * `aturing` should be added to the `tape` group
# * `edijkstra` should be added to the `tcpdump` group.
# * `alovelace` should be added to the `audio` and `video` groups.
# * `ghopper` should be in the `audio` group, but not in the `video` group.
