---
- name: Configure the web server(s) according to specs
  hosts: web
  become: true
  vars_files:
    - vars/secret.yml
  roles:
    - web

- name: Configure the database server(s) according to specs
  hosts: db
  become: true
  roles:
    - db
